// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: SquareLine

#ifndef _SQUARELINE_UI_H
#define _SQUARELINE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_BrewingScreen;
extern lv_obj_t *ui_Fill;
extern lv_obj_t *ui_Border;
extern lv_obj_t *ui_MainContainer;
extern lv_obj_t *ui_TimerAndWeightsContainer;
extern lv_obj_t *ui_TimerLabel;
extern lv_obj_t *ui_WeightsLabel;
extern lv_obj_t *ui_Loader;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
