// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: rounded-weights

#ifndef _ROUNDED_WEIGHTS_UI_H
#define _ROUNDED_WEIGHTS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void fill_Animation( lv_obj_t *TargetObject, int delay);

// SCREEN: ui_BrewingScreen
void ui_BrewingScreen_screen_init(void);
void ui_event_BrewingScreen( lv_event_t * e);
extern lv_obj_t *ui_BrewingScreen;
extern lv_obj_t *ui_Fill;
extern lv_obj_t *ui_Border;
extern lv_obj_t *ui_MainContainer;
extern lv_obj_t *ui_TimerAndWeightsContainer;
extern lv_obj_t *ui_TimerLabel;
extern lv_obj_t *ui_WeightsContainer;
extern lv_obj_t *ui_WeightsLabel;
extern lv_obj_t *ui_WeightsUnitsLabel;
extern lv_obj_t *ui_Loader;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
