// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: rounded-weights

#include "ui.h"

void ui_BrewingScreen_screen_init(void)
{
ui_BrewingScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_BrewingScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BrewingScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BrewingScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Fill = lv_obj_create(ui_BrewingScreen);
lv_obj_set_width( ui_Fill, 240);
lv_obj_set_height( ui_Fill, 16);
lv_obj_set_align( ui_Fill, LV_ALIGN_BOTTOM_MID );
lv_obj_clear_flag( ui_Fill, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Fill, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Fill, lv_color_hex(0x51C263), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Fill, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Border = lv_arc_create(ui_BrewingScreen);
lv_obj_set_width( ui_Border, 244);
lv_obj_set_height( ui_Border, 244);
lv_obj_set_align( ui_Border, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Border, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_Border, LV_SCROLLBAR_MODE_OFF);
lv_arc_set_value(ui_Border, 50);

lv_obj_set_style_bg_color(ui_Border, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Border, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_MainContainer = lv_obj_create(ui_BrewingScreen);
lv_obj_remove_style_all(ui_MainContainer);
lv_obj_set_width( ui_MainContainer, 240);
lv_obj_set_height( ui_MainContainer, 240);
lv_obj_set_align( ui_MainContainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_MainContainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_MainContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_MainContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TimerAndWeightsContainer = lv_obj_create(ui_MainContainer);
lv_obj_remove_style_all(ui_TimerAndWeightsContainer);
lv_obj_set_width( ui_TimerAndWeightsContainer, 160);
lv_obj_set_height( ui_TimerAndWeightsContainer, 105);
lv_obj_set_align( ui_TimerAndWeightsContainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_TimerAndWeightsContainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_TimerAndWeightsContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_TimerAndWeightsContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_TimerAndWeightsContainer, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TimerAndWeightsContainer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TimerAndWeightsContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TimerLabel = lv_label_create(ui_TimerAndWeightsContainer);
lv_obj_set_width( ui_TimerLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TimerLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TimerLabel, 0 );
lv_obj_set_y( ui_TimerLabel, -20 );
lv_obj_set_align( ui_TimerLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_TimerLabel,"03:00");
lv_obj_clear_flag( ui_TimerLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_text_font(ui_TimerLabel, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WeightsLabel = lv_label_create(ui_TimerAndWeightsContainer);
lv_obj_set_width( ui_WeightsLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WeightsLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WeightsLabel, 0 );
lv_obj_set_y( ui_WeightsLabel, 20 );
lv_obj_set_align( ui_WeightsLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_WeightsLabel,"100.1");
lv_obj_set_style_text_font(ui_WeightsLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Loader = lv_spinner_create(ui_MainContainer,1000,90);
lv_obj_set_width( ui_Loader, 30);
lv_obj_set_height( ui_Loader, 30);
lv_obj_set_x( ui_Loader, -4 );
lv_obj_set_y( ui_Loader, 52 );
lv_obj_set_align( ui_Loader, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Loader, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_arc_width(ui_Loader, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_width(ui_Loader, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_Loader, true, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_BrewingScreen, ui_event_BrewingScreen, LV_EVENT_ALL, NULL);

}
